stages: 
  data_ingestion: 
    cmd: python src/pipline/data_ingestion_pipline.py
    deps:
      - src/pipline/data_ingestion_pipline.py
      - config/config.yaml
    outs: 
      - artifacts/data_ingestion/train.csv
      - artifacts/data_ingestion/test.csv
      - artifacts/data_ingestion/raw.csv  
