stages: 
  data_ingestion: 
    cmd: python src/pipline/Train_pipline.py
    deps:
      - src/pipline/Train_pipline.py
      - config/config.yaml
    outs: 
      - artifacts/data_ingestion/train.csv
      - artifacts/data_ingestion/test.csv
      - artifacts/data_ingestion/raw.csv  

  # data_transformation:
  #   cmd: python src/pipline/Train_pipline.py
  #   deps:
  #     - src/pipline/Train_pipline.py
  #     - config/config.yaml
  #     - params.yaml
  #   outs: 
  #     - artifacts/data_transformation/train.npy
  #     - artifacts/data_transformation/test.npy
  #     - artifacts/data_transformation/preprocess.pkl 
  # model_train:
  #   cmd: python src/pipline/Train_pipline.py
  #   deps:
  #    - src/pipline/Train_pipline.py
  #    - config/config.yaml
  #    - artifacts/data_transformation/train.npy
  #    - artifacts/data_transformation/test.npy
  #   outs:
  #    - artifacts/model_train/model.pkl

