Artifacts_root: artifacts

Data_Ingestion:
  dir: artifacts/data_ingestion
  train_data: artifacts/data_ingestion/train.csv
  test_data: artifacts/data_ingestion/test.csv
  raw_data: artifacts/data_ingestion/raw.csv

Data_Trnsformation:
  dir: artifacts/data_transformation
  train_data: artifacts/data_ingestion/train.csv
  test_data: artifacts/data_ingestion/test.csv
  train_arr: artifacts/data_transformation/train.npy
  test_arr: artifacts/data_transformation/test.npy
  preprocess_obj: artifacts/data_transformation/preprocess.pkl

Model_Train:
  dir: artifacts/model_train
  train_arr: artifacts/data_transformation/train.npy
  test_arr: artifacts/data_transformation/test.npy
  model: artifacts/model_train/model.pkl
